name: template-small
container:
  port: 5432
  name:
    default: template-small
    primary: primary
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: radondb
  container: radondb-postgres
  tag: centos8-13.3-4.7.1
resources:
  cpu: 200m
  memory: 512Mi
persistence:
  accessModes: ReadWriteMany
