name: primary
container:
  port: 5432
  name: primary
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: qingcloud
  container: qingcloud-postgres
  tag: centos8-13.3-4.7.1
resources:
  cpu: 200m
  memory: 512Mi
