apiVersion: v1
name: primary-replica
description: Deploy a basic radondb primary and replica cluster
version: 1
appVersion: 4.7.1
keywords:
- postgresql
- postgres
- database
- sql
home: https://www.radondb.com/
icon: https://www.radondb.com/images/logo.svg
sources:
- https://github.com/RadondbData/radondb-containers
