apiVersion: v1
name: primary-replica
description: Deploy a basic radondb primary and replica cluster
version: 1
appVersion: 5.0.5
keywords:
- postgresql
- postgres
- database
- sql
home: https://www.radondb.com/
icon: https://xenondb.pek3b.qingstor.com/icons/radondb-mysql.svg
sources:
- https://github.com/radondb/radondb-postgresql-operator
