name: primary-replica
container:
  port: 5432
  name:
    primary: primary
    replica: replica
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: qingcloud
  container: qingcloud-postgres
  tag: centos8-11.12-4.7.1
pv:
  storage: 400M
  name: primary-pv
  mode: ReadWriteMany
  path: /data
pvc:
  name: primary-pvc
resources:
  cpu: 200m
  memory: 512Mi
